/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.wedroid.framework;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int click_remove_id=0x7f010010;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int collapsed_height=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_enabled=0x7f01000a;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_handle_id=0x7f01000e;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_scroll_start=0x7f010001;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>onDown</code></td><td>0</td><td></td></tr>
<tr><td><code>onMove</code></td><td>1</td><td></td></tr>
<tr><td><code>onLongPress</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int drag_start_mode=0x7f01000d;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drop_animation_duration=0x7f010009;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fling_handle_id=0x7f01000f;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int float_alpha=0x7f010006;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int float_background_color=0x7f010003;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int max_drag_scroll_speed=0x7f010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int remove_animation_duration=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int remove_enabled=0x7f01000c;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>clickRemove</code></td><td>0</td><td></td></tr>
<tr><td><code>flingRemove</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int remove_mode=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int slide_shuffle_speed=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int sort_enabled=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int track_drag_sort=0x7f010005;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int use_default_controller=0x7f010011;
    }
    public static final class dimen {
        /** 
         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static int activity_horizontal_margin=0x7f04000a;
        public static int dimen_sp_06=0x7f040000;
        public static int dimen_sp_08=0x7f040001;
        public static int dimen_sp_10=0x7f040002;
        public static int dimen_sp_12=0x7f040003;
        public static int dimen_sp_14=0x7f040004;
        public static int dimen_sp_16=0x7f040005;
        public static int dimen_sp_18=0x7f040006;
        public static int dimen_sp_20=0x7f040007;
        public static int dimen_sp_22=0x7f040008;
        public static int dimen_sp_24=0x7f040009;
    }
    public static final class drawable {
        public static int ic_launcher=0x7f020000;
        public static int xlistview_arrow=0x7f020001;
        public static int z_arrow_down=0x7f020002;
        public static int z_arrow_up=0x7f020003;
    }
    public static final class id {
        public static int action_settings=0x7f08000f;
        public static int clickRemove=0x7f080000;
        public static int flingRemove=0x7f080001;
        public static int onDown=0x7f080002;
        public static int onLongPress=0x7f080003;
        public static int onMove=0x7f080004;
        public static int toast_text=0x7f080005;
        public static int xlistview_footer_content=0x7f080006;
        public static int xlistview_footer_hint_textview=0x7f080008;
        public static int xlistview_footer_progressbar=0x7f080007;
        public static int xlistview_header_arrow=0x7f08000d;
        public static int xlistview_header_content=0x7f080009;
        public static int xlistview_header_hint_textview=0x7f08000b;
        public static int xlistview_header_progressbar=0x7f08000e;
        public static int xlistview_header_text=0x7f08000a;
        public static int xlistview_header_time=0x7f08000c;
    }
    public static final class layout {
        public static int common_toast=0x7f030000;
        public static int toast_styles=0x7f030001;
        public static int xlistview_footer=0x7f030002;
        public static int xlistview_header=0x7f030003;
    }
    public static final class menu {
        public static int main=0x7f070000;
    }
    public static final class string {
        public static int action_settings=0x7f050002;
        public static int app_name=0x7f050000;
        public static int hello_world=0x7f050001;
        public static int sk_time_before_yesterday=0x7f05000a;
        public static int sk_time_fri=0x7f05000f;
        public static int sk_time_monday=0x7f05000b;
        public static int sk_time_sta=0x7f050010;
        public static int sk_time_sun=0x7f050011;
        public static int sk_time_thu=0x7f05000e;
        public static int sk_time_tud=0x7f05000c;
        public static int sk_time_won=0x7f05000d;
        public static int sk_time_yesterday=0x7f050009;
        public static int xlistview_footer_hint_normal=0x7f050007;
        public static int xlistview_footer_hint_ready=0x7f050008;
        public static int xlistview_header_hint_loading=0x7f050005;
        public static int xlistview_header_hint_normal=0x7f050003;
        public static int xlistview_header_hint_ready=0x7f050004;
        public static int xlistview_header_last_time=0x7f050006;
    }
    public static final class style {
        public static int AppBaseTheme=0x7f060003;
        public static int AppTheme=0x7f060004;
        /**  透明的无标题栏背景 
         */
        public static int Theme_Translucent=0x7f060001;
        /**  透明的背景 
         */
        public static int Theme_Translucent_NoTitle=0x7f060000;
        public static int launch_dialog=0x7f060002;
    }
    public static final class styleable {
        /**  DragSortListView 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #DragSortListView_click_remove_id com.wedroid.framework:click_remove_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_collapsed_height com.wedroid.framework:collapsed_height}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_enabled com.wedroid.framework:drag_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_handle_id com.wedroid.framework:drag_handle_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_scroll_start com.wedroid.framework:drag_scroll_start}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_start_mode com.wedroid.framework:drag_start_mode}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drop_animation_duration com.wedroid.framework:drop_animation_duration}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_fling_handle_id com.wedroid.framework:fling_handle_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_float_alpha com.wedroid.framework:float_alpha}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_float_background_color com.wedroid.framework:float_background_color}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_max_drag_scroll_speed com.wedroid.framework:max_drag_scroll_speed}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_animation_duration com.wedroid.framework:remove_animation_duration}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_enabled com.wedroid.framework:remove_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_mode com.wedroid.framework:remove_mode}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_slide_shuffle_speed com.wedroid.framework:slide_shuffle_speed}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_sort_enabled com.wedroid.framework:sort_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_track_drag_sort com.wedroid.framework:track_drag_sort}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_use_default_controller com.wedroid.framework:use_default_controller}</code></td><td></td></tr>
           </table>
           @see #DragSortListView_click_remove_id
           @see #DragSortListView_collapsed_height
           @see #DragSortListView_drag_enabled
           @see #DragSortListView_drag_handle_id
           @see #DragSortListView_drag_scroll_start
           @see #DragSortListView_drag_start_mode
           @see #DragSortListView_drop_animation_duration
           @see #DragSortListView_fling_handle_id
           @see #DragSortListView_float_alpha
           @see #DragSortListView_float_background_color
           @see #DragSortListView_max_drag_scroll_speed
           @see #DragSortListView_remove_animation_duration
           @see #DragSortListView_remove_enabled
           @see #DragSortListView_remove_mode
           @see #DragSortListView_slide_shuffle_speed
           @see #DragSortListView_sort_enabled
           @see #DragSortListView_track_drag_sort
           @see #DragSortListView_use_default_controller
         */
        public static final int[] DragSortListView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f,
            0x7f010010, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#click_remove_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:click_remove_id
        */
        public static int DragSortListView_click_remove_id = 16;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#collapsed_height}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:collapsed_height
        */
        public static int DragSortListView_collapsed_height = 0;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#drag_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:drag_enabled
        */
        public static int DragSortListView_drag_enabled = 10;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#drag_handle_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:drag_handle_id
        */
        public static int DragSortListView_drag_handle_id = 14;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#drag_scroll_start}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:drag_scroll_start
        */
        public static int DragSortListView_drag_scroll_start = 1;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#drag_start_mode}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>onDown</code></td><td>0</td><td></td></tr>
<tr><td><code>onMove</code></td><td>1</td><td></td></tr>
<tr><td><code>onLongPress</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.wedroid.framework:drag_start_mode
        */
        public static int DragSortListView_drag_start_mode = 13;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#drop_animation_duration}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:drop_animation_duration
        */
        public static int DragSortListView_drop_animation_duration = 9;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#fling_handle_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:fling_handle_id
        */
        public static int DragSortListView_fling_handle_id = 15;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#float_alpha}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:float_alpha
        */
        public static int DragSortListView_float_alpha = 6;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#float_background_color}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:float_background_color
        */
        public static int DragSortListView_float_background_color = 3;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#max_drag_scroll_speed}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:max_drag_scroll_speed
        */
        public static int DragSortListView_max_drag_scroll_speed = 2;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#remove_animation_duration}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:remove_animation_duration
        */
        public static int DragSortListView_remove_animation_duration = 8;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#remove_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:remove_enabled
        */
        public static int DragSortListView_remove_enabled = 12;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#remove_mode}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>clickRemove</code></td><td>0</td><td></td></tr>
<tr><td><code>flingRemove</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.wedroid.framework:remove_mode
        */
        public static int DragSortListView_remove_mode = 4;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#slide_shuffle_speed}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:slide_shuffle_speed
        */
        public static int DragSortListView_slide_shuffle_speed = 7;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#sort_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:sort_enabled
        */
        public static int DragSortListView_sort_enabled = 11;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#track_drag_sort}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:track_drag_sort
        */
        public static int DragSortListView_track_drag_sort = 5;
        /**
          <p>This symbol is the offset where the {@link com.wedroid.framework.R.attr#use_default_controller}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.wedroid.framework:use_default_controller
        */
        public static int DragSortListView_use_default_controller = 17;
    };
}
